version: 2

sources:
  - name: raw_src
    freshness:
      warn_after: {count: 1, period: minute}
      error_after: {count: 1, period: hour}
    loaded_at_field: _loaded_ts
    tables:
      - name: t1
        columns:
          - name: id
            tests:
              # - unique
              - not_null
      - name: t2
        columns:
          - name: id
            tests:
              - unique
              - not_null
